project_name: deluge-remove-after
builds:
- binary: deluge-remove-after
  goos:
    - linux
    - windows
    - freebsd
  goarch:
    - arm
    - arm64
    - amd64
  tags:
    - netgo
    - static_build
  env:
    - CGO_ENABLED=0
  ldflags: -s -w -X main.version=v{{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
nfpms:
  - homepage: https://github.com/lrstanley/deluge-remove-after
    maintainer: Liam Stanley <me@liamstanley.io>
    description: deluge-remove-after -- daemon for removing torrents from deluge after a specified timeframe
    license: MIT
    formats: [deb, rpm]
    bindir: /usr/bin
archives:
  - id: tgz
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
snapshot:
  name_template: snapshot-{{.Commit}}
